In [1]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj=Demo()
obj.test()

test() for the class and method


In [12]:
def test():
    print("test() for function")
    return
test()

test() for function


In [13]:
class Demo1:
    def fact(self,n):
        fact = 1
        while(n!=0):
            fact=fact * n
            n = n-1
        return fact
p1=Demo1()
p1.fact(5)


120

In [11]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
        
    def add(self,p1,p2):
            return p1+p2
        
c1=Demo2(10,20)
print(c1.add(100,200))

300


In [8]:
class Person(object):
    def __init__(self,name):
        self.name=name
    def getName(self):
        return self.name
    def isEmployee(self):
        return False
class Employee(Person):
    def isEmployee(self):
        return True
emp=Person("Anil")
print(emp.getName(),emp.isEmployee())
emp1=Person("Chiikar")
print(emp1.getName(),emp1.isEmployee())

Anil False
Chiikar False


## NumPy

In [12]:
lst=[1,2,3,4]
print(lst)
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)
print(array.dtype)
print(array.shape)

[1, 2, 3, 4]
[1 2 3 4]
int32
(4,)


In [23]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])

b=np.array([[10,20,30],[40,50,60]])
c=np.array(a+b)
print(c)
c.reshape(3,2)

[[11 22 33]
 [44 55 66]]


array([[11, 22],
       [33, 44],
       [55, 66]])

In [24]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [29]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a3=np.array([8,9,10])
print(np.vstack((a1,a2,a3)))

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]]


In [25]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [27]:
a1=np.random.normal(5,0.5,10)
print(a1)

[5.56983789 4.90251755 4.8723645  5.07364726 4.78177358 5.03142
 5.26798987 5.00413182 5.2267845  5.38937191]


In [48]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a3=np.array([7,8,10])
print(np.diagonal((a1,a2,a3)))
print(np.trace((a1,a2,a3)))

[ 1  5 10]
16


In [49]:
import numpy as np
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [50]:
np.arange(1,20,5)

array([ 1,  6, 11, 16])

In [51]:
np.arange(1,2048,564)
np.arange(1,20,5)

array([ 1,  6, 11, 16])

In [52]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column :",a1[:,1])

slicing column : [2 5]


In [53]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column :",a1[:,2])

slicing column : [3 6]


In [54]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row :",a1[0])

first row : [1 2 3]


In [55]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row :",a1[1])

second row : [4 5 6]


In [57]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [58]:
a1=np.random.normal(5,1,10)
print(a1)
print("Min value=",np.min(a1))
print("Max value=",np.max(a1))
print("Mean value=",np.mean(a1))
print("Median Value=",np.median(a1))

[4.65281965 5.05602039 2.44121406 6.25954878 3.57055431 3.07102883
 6.26289001 4.59440802 4.48138621 5.06366666]
Min value= 2.4412140603086208
Max value= 6.262890012766473
Mean value= 4.545353692299339
Median Value= 4.623613837689678


In [69]:
c1=np.array(([1,2],[4,5]))
c2=np.array(([4,5],[4,7]))
np.dot(c1,c2)

array([[12, 19],
       [36, 55]])

In [1]:
import pandas as pd
dict={"Name":["Chiikar","Surya","Mohit","Guddu"],
       "Email ID":["chiikar@mabbu.com","Surya@Great.com","Mohit@gangleader.com","Guddu@sate.com"],
       "Mobile Number":["12345678910","1235467098","6543217890","3467853643"],
       "Address":["Hyd","Hyd","Hyd","Hyd"]}
b=pd.DataFrame(dict)
print(b)

      Name              Email ID Mobile Number Address
0  Chiikar     chiikar@mabbu.com   12345678910     Hyd
1    Surya       Surya@Great.com    1235467098     Hyd
2    Mohit  Mohit@gangleader.com    6543217890     Hyd
3    Guddu        Guddu@sate.com    3467853643     Hyd


## 1. Lets input as string--> Fequency of charfrom 0to9
## Input: 213abc456def111
## Output: 0 4 1 1 1 1 1 0 0 0 
## 2. Check if the two strings are Anagrams
## abc cba-->{a:1} {b:1} {c:1}-- True
## aabbcc   ccbbaa--False